version: "3.9"

services:

  postgres-user:
    image: postgres:16
    container_name: postgres-user
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - taskflow-network

  postgres-project:
    image: postgres:16
    container_name: postgres-project
    restart: always
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-project-data:/var/lib/postgresql/data
    networks:
      - taskflow-network

  permify:
    image: ghcr.io/permify/permify:latest
    container_name: permify
    ports:
      - "3476:3476"
      - "3478:3478"
    networks:
      - taskflow-network

volumes:
  postgres-user-data:
  postgres-project-data:

networks:
  taskflow-network:
    driver: bridge