server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-project:5432/projectdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false